# Data

## Description

### Data Sources
Website: The World Bank Group

To analyze country-wise CO<sub>2</sub> emissions, various metrics that influence and correlate with CO<sub>2</sub> release have been considered. The dataset includes information on forest area percentage, fossil fuel consumption percentage, trade metrics (imports and exports), livestock production, and air pollution levels. Additionally, data on countries' income levels, GDP, and renewable energy usage has been gathered to examine the factors and trends contributing to CO<sub>2</sub> emissions.

The raw data from the World Bank Group website was downloaded as CSV files.

**Data Links and Collection:**

- [CO<sub>2</sub> Emissions](https://data.worldbank.org/indicator/EN.GHG.CO2.MT.CE.AR5) (megatonnes)
- [Forest Area](https://data.worldbank.org/indicator/AG.LND.FRST.ZS) (% of land area)
- [Fossil Fuel Energy Consumption](https://data.worldbank.org/indicator/EG.USE.COMM.FO.ZS) (% of total energy consumption by country)
- [Imports of Goods and Services](https://data.worldbank.org/indicator/BM.GSR.GNFS.CD) (US dollars)
- [Exports of Goods and Services](https://data.worldbank.org/indicator/BX.GSR.TOTL.CD) (US dollars)
- [Livestock Production Index](https://data.worldbank.org/indicator/AG.PRD.LVSK.XD) (Baseline Index: 100)
- [Air Pollution](https://data.worldbank.org/indicator/EN.ATM.PM25.MC.M3) (micrograms/m<sup>3</sup>)
- [GDP](https://data.worldbank.org/indicator/NY.GDP.MKTP.CD) (US dollars)
- [Renewable Energy Consumption](https://data.worldbank.org/indicator/EG.FEC.RNEW.ZS) (% of total energy consumption by country)
- **Income Level**: Obtained from the zip folder as a separate CSV file after downloading the data (Low, Lower middle, Upper middle, High)

### Data Format
- Carbon Emissions: A measure of annual emissions of carbon dioxide (CO2) in megatonnes, one of the six Kyoto greenhouse gases (GHG) from 1970 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Forest Area: An annual percentage metric of forest area land, excluding agricultural production systems, from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Fossil Fuel Energy Consumption: An annual percentage metric of Fossil fuel (comprises coal, oil, petroleum, and natural gas products) consumption from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Imports of Goods and Services: An annual measure of goods and services transacted between residents of a country and the rest of the world in US dollars from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Exports of Goods and Services: An annual measure of goods exports, service exports and primary income receipts in US dollars from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Livestock Production Index: An annual measure of the Livestock production index that includes meat and milk from all sources, dairy products such as cheese, and eggs, honey, raw silk, wool, and hides and skins from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Air Pollution: A measure of the mean annual exposure (micrograms per cubic meter) of a nation's population to concentrations of suspended particles measuring less than 2.5 microns in aerodynamic diameter, which are capable of causing severe health damage. Data has been collected from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- GDP: The annual gross domestic product in US dollars from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Renewable Energy Consumption: The share of renewables energy in total final energy consumption measured by the percentage of total energy consumption from 1960 to 2023 for 266 countries and regions. The dataset contains Country Name, Country Code, Indicator Name, Indicator Code, and the Years.

- Income Level: A dataset indicating the income level of countries as High, Low, Upper Middle, and Lower Middle income for 265 countries and regions. The dataset contains the Conutry Code, Region, Income Group, Special Notes and Table Name.

### Data Preprocessing
After importing the data:

- The columns are filtered to only include data from years 1990 - 2020
- The data frames are converted to long format
- All metrics data frames are joined on ‘Country Codes’ to obtain the final dataset
- The data frame is exported as a CSV file

[Link to Preprocessing script on Python](data_preprocessing/Data_Preprocessing.html)

## Missing value analysis
