# Results

Continent-Wise CO<sub>2</sub> Emissions Over 3 Decades
```{r}
#| warning: false

library(countrycode)
library(dplyr)
library(ggplot2)
library(forcats)

emissions_df = read.csv("emission_analysis.csv")

emissions_df_g1 <- emissions_df

# For this purpose, we are filling all missing CO2 emission values with 0
emissions_df_g1$CO2_Emissions[is.na(emissions_df_g1$CO2_Emissions)] <- 0

# Obtaining Continents
emissions_df_g1$Continent <- countrycode(sourcevar = emissions_df_g1[, "Country.Code"],
                           origin = "iso3c",
                           destination = "continent")

# Adding decade ranges and aggregating CO2 emissions
emissions_df_g1 <- emissions_df_g1 |>
  mutate(
    Year_Range = case_when(
      Year >= 1990 & Year <= 2000 ~ "1990-2000",
      Year >= 2000 & Year <= 2010 ~ "2000-2010",
      Year >= 2010 & Year <= 2020 ~ "2010-2020")) |>
  group_by(Continent, Year_Range) |>                
  summarise(Aggregate_CO2 = sum(CO2_Emissions)) |>
  ungroup()

ggplot(emissions_df_g1, aes(x = Aggregate_CO2, y = fct_reorder(Continent, Aggregate_CO2))) +
  geom_col(fill = "cornflowerblue") +
  facet_wrap(~Year_Range) +
  labs(title = expression("Continent-Wise CO"[2] ~ "Emissions Over 3 Decades"), x = "Aggregate CO2 Emissions (megatonnes)", y = "Continents")

```
From the graph above we can study the amount and distribution of CO<sub>2</sub> emissions over 3 decades across different continents.
In all facets, we observe the same order of CO<sub>2</sub> emission amounts with Asia having the highest amount due to the continent have the most number of countries, and Oceania (Australia and New Zealand) having the least amount.
The amount of CO<sub>2</sub> emissions in Asia steadily increased each decade and reached an alarming 200k megatonnes, which indicates that Asia plays a huge role in pollution.
However, the amount of CO<sub>2</sub> emissions in Europe decreased over each decade, having its highest emissions in 1990-2000. This shows a slow down in CO<sub>2</sub> emission activity in this continent.
The amount of CO<sub>2</sub> emissions in Africa slightly increased each decade, while they remained almost the same in the Americas and Oceania from 1990-2020.